name: e-commerce-mern

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    env_file:
      - ./backend/${ENV_FILE:-'.env'}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV:-production}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
