version: "3"

services:
  # Backend service
  backend:
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost:4000
    ports:
      - "4000:4000"

  # Frontend service
  frontend:
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    ports:
      - "3000:80"

  # Admin service
  admin:
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "8080:80" 
