version: "3"

services:
  # Backend service
  backend:
    build: ./backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}
      - REFRESH_TOKEN_EXPIRE=${REFRESH_TOKEN_EXPIRE}
      - COOKIE_EXPIRE=${COOKIE_EXPIRE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - FRONTEND_URL=http://159.65.230.12
    volumes:
      - ./backend/upload:/app/upload
    networks:
      - app-network
    ports:
      - "4000:4000"

  # Frontend service
  frontend:
    build: ./frontend
    restart: always
    environment:
      - REACT_APP_API_URL=http://159.65.230.12/api
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "80:80"

  # Admin service
  admin:
    build: ./admin
    restart: always
    environment:
      - VITE_API_URL=http://159.65.230.12/api
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8080:80"

# Docker Networks
networks:
  app-network:
    driver: bridge
