name: e-commerce-mern

services:
  nginx-proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/live:/etc/ssl:ro
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - frontend
      - admin
      - api

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    image: ${DOCKER_USERNAME:-arnaudhalvick}/e-commerce-api:latest
    restart: always
    env_file:
      - ./backend/${ENV_FILE:-.env}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - USE_HTTPS=true
      - HTTPS_PORT=4443
      - FRONTEND_URL=https://mernappshopper.xyz
      - PUBLIC_URL=https://mernappshopper.xyz
      - ADMIN_URL=https://admin.mernappshopper.xyz
      # No secrets in environment variables - loaded from files in entrypoint script
    ports:
      - "4000:4000"
      - "4443:4443"
    depends_on:
      - mongo
    volumes:
      - ./ssl/live/mernappshopper.xyz:/app/ssl:ro
      - product_images:/app/upload/images
      - ./secrets:/app/secrets:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV:-production}
        - REACT_APP_API_URL=${REACT_APP_API_URL:-https://mernappshopper.xyz}
    image: ${DOCKER_USERNAME:-arnaudhalvick}/e-commerce-frontend:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secrets:/run/secrets:ro
    environment:
      - API_URL=${API_URL:-https://mernappshopper.xyz}
    depends_on:
      - api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        - VITE_ENV=${VITE_ENV:-production}
        - VITE_API_URL=${VITE_API_URL:-https://mernappshopper.xyz}
        - VITE_BASE_PATH=/
    image: ${DOCKER_USERNAME:-arnaudhalvick}/e-commerce-admin:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./admin/admin-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secrets:/run/secrets:ro
    environment:
      - API_URL=${API_URL:-https://mernappshopper.xyz}
    depends_on:
      - api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  product_images:
