name: e-commerce-mern-dev

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=4001
      - HTTPS_PORT=4443
      - FRONTEND_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost:4001
      - MONGO_URI=mongodb://mongo:27017/e-commerce
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./secrets:/app/secrets:ro
    ports:
      - "4001:4001"
      - "4443:4443"
    depends_on:
      - mongo
    networks:
      - app-network
    command: npm run dev:docker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./secrets:/app/secrets:ro
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4001
      - REACT_APP_ENV=development
      - REACT_APP_DEFAULT_PROTOCOL=http
      - REACT_APP_USE_HTTPS=false
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network
    command: npm run dev:docker

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    volumes:
      - ./admin:/app
      - /app/node_modules
      - ./secrets:/app/secrets:ro
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4001
      - VITE_BASE_PATH=/
      - VITE_ADMIN_API_PATH=/api/admin
      - VITE_DEV_SERVER_PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - app-network
    command: npm run dev:docker

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
