// Action types for product context
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RESTORE_PRODUCT = "RESTORE_PRODUCT";
export const TOGGLE_PRODUCT_AVAILABILITY = "TOGGLE_PRODUCT_AVAILABILITY";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const CLEAR_PRODUCT_ERROR = "CLEAR_PRODUCT_ERROR";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const CLEAR_CURRENT_PRODUCT = "CLEAR_CURRENT_PRODUCT";
